airlineIATAs = [
	{ "iata": "M3", "airline": "ABSA Cargo Airline" },
	{ "iata": "GB", "airline": "ABX Air" },
	{ "iata": "9T", "airline": "ACT Airlines" },
	{ "iata": "9N", "airline": "ANA & JP Express" },
	{ "iata": "V8", "airline": "ATRAN Cargo Airlines" },
	{ "iata": "2E", "airline": "AVE.com" },
	{ "iata": "K5", "airline": "Aban Air" },
	{ "iata": "W9", "airline": "Abelag Aviation" },
	{ "iata": "MO", "airline": "Abu Dhabi Amiri Flight" },
	{ "iata": "ZY", "airline": "Ada Air" },
	{ "iata": "JP", "airline": "Adria Airways" },
	{ "iata": "A3", "airline": "Aegean Airlines" },
	{ "iata": "RE", "airline": "Aer Arann" },
	{ "iata": "EI", "airline": "Aer Lingus" },
	{ "iata": "E4", "airline": "Aero Asia International" },
	{ "iata": "EM", "airline": "Aero Benin" },
	{ "iata": "7L", "airline": "Aero Caribbean" },
	{ "iata": "Q6", "airline": "Aero Condor Peru" },
	{ "iata": "AJ", "airline": "Aero Contractors" },
	{ "iata": "QL", "airline": "Aero Lanka" },
	{ "iata": "M0", "airline": "Aero Mongolia" },
	{ "iata": "W4", "airline": "Aero Services Executive" },
	{ "iata": "DW", "airline": "Aero-Charter Ukraine" },
	{ "iata": "BF", "airline": "Aero-Service" },
	{ "iata": "HC", "airline": "Aero-Tropics Air Services" },
	{ "iata": "3S", "airline": "AeroLogic" },
	{ "iata": "AM", "airline": "AeroMéxico" },
	{ "iata": "P5", "airline": "AeroRepublica" },
	{ "iata": "6N", "airline": "AeroSucre" },
	{ "iata": "2B", "airline": "Aerocondor" },
	{ "iata": "SU", "airline": "Aeroflot Russian Airlines" },
	{ "iata": "SU", "airline": "Aeroflot-Cargo" },
	{ "iata": "D9", "airline": "Aeroflot-Don" },
	{ "iata": "5N", "airline": "Aeroflot-Nord" },
	{ "iata": "KG", "airline": "Aerogaviota" },
	{ "iata": "AR", "airline": "Aerolineas Argentinas" },
	{ "iata": "2K", "airline": "Aerolineas Galapagos (Aerogal)" },
	{ "iata": "P4", "airline": "Aerolineas Sosa" },
	{ "iata": "VW", "airline": "Aeromar" },
	{ "iata": "QO", "airline": "Aeromexpress" },
	{ "iata": "HT", "airline": "Aeromist-Kharkiv" },
	{ "iata": "5D", "airline": "Aeroméxico Connect" },
	{ "iata": "OT", "airline": "Aeropelican Air Services" },
	{ "iata": "WL", "airline": "Aeroperlas" },
	{ "iata": "VH", "airline": "Aeropostal Alas de Venezuela" },
	{ "iata": "5L", "airline": "Aerosur" },
	{ "iata": "VV", "airline": "Aerosvit Airlines" },
	{ "iata": "FK", "airline": "Africa West" },
	{ "iata": "XU", "airline": "African Express Airways" },
	{ "iata": "6F", "airline": "Afrijet Airlines" },
	{ "iata": "Q9", "airline": "Afrinat International Airlines" },
	{ "iata": "8U", "airline": "Afriqiyah Airways" },
	{ "iata": "ZI", "airline": "Aigle Azur" },
	{ "iata": "AH", "airline": "Air Algerie" },
	{ "iata": "GD", "airline": "Air Alpha Greenland" },
	{ "iata": "A6", "airline": "Air Alps Aviation" },
	{ "iata": "G9", "airline": "Air Arabia" },
	{ "iata": "QN", "airline": "Air Armenia" },
	{ "iata": "KC", "airline": "Air Astana" },
	{ "iata": "CC", "airline": "Air Atlanta Icelandic" },
	{ "iata": "KI", "airline": "Air Atlantique" },
	{ "iata": "UU", "airline": "Air Austral" },
	{ "iata": "W9", "airline": "Air Bagan" },
	{ "iata": "BT", "airline": "Air Baltic" },
	{ "iata": "AB", "airline": "Air Berlin" },
	{ "iata": "BP", "airline": "Air Botswana" },
	{ "iata": "2J", "airline": "Air Burkina" },
	{ "iata": "TY", "airline": "Air Caledonie" },
	{ "iata": "AC", "airline": "Air Canada" },
	{ "iata": "QK", "airline": "Air Canada Jazz" },
	{ "iata": "TX", "airline": "Air Caraibes" },
	{ "iata": "2Q", "airline": "Air Cargo Carriers" },
	{ "iata": "NV", "airline": "Air Central" },
	{ "iata": "CV", "airline": "Air Chathams" },
	{ "iata": "CA", "airline": "Air China" },
	{ "iata": "CA", "airline": "Air China Cargo" },
	{ "iata": "QD", "airline": "Air Class Lineas Aereas" },
	{ "iata": "A7", "airline": "Air Comet" },
	{ "iata": "AG", "airline": "Air Contractors" },
	{ "iata": "QC", "airline": "Air Corridor" },
	{ "iata": "YN", "airline": "Air Creebec" },
	{ "iata": "EN", "airline": "Air Dolomiti" },
	{ "iata": "UX", "airline": "Air Europa" },
	{ "iata": "PC", "airline": "Air Fiji" },
	{ "iata": "OF", "airline": "Air Finland" },
	{ "iata": "AF", "airline": "Air France" },
	{ "iata": "AF", "airline": "Air Freight NZ" },
	{ "iata": "ZX", "airline": "Air Georgian" },
	{ "iata": "7T", "airline": "Air Glaciers" },
	{ "iata": "GL", "airline": "Air Greenland" },
	{ "iata": "LQ", "airline": "Air Guinea Cargo" },
	{ "iata": "GG", "airline": "Air Guyane Express" },
	{ "iata": "LD", "airline": "Air Hong Kong" },
	{ "iata": "8C", "airline": "Air Horizon" },
	{ "iata": "NY", "airline": "Air Iceland (Flugfélag Íslands)" },
	{ "iata": "AI", "airline": "Air India" },
	{ "iata": "IX", "airline": "Air India Express" },
	{ "iata": "CD", "airline": "Air India Regional" },
	{ "iata": "3H", "airline": "Air Inuit" },
	{ "iata": "I9", "airline": "Air Italy" },
	{ "iata": "4Q", "airline": "Air Italy Polska" },
	{ "iata": "VU", "airline": "Air Ivoire" },
	{ "iata": "JM", "airline": "Air Jamaica" },
	{ "iata": "NQ", "airline": "Air Japan" },
	{ "iata": "4A", "airline": "Air Kiribati" },
	{ "iata": "0K", "airline": "Air Kokshetau" },
	{ "iata": "JS", "airline": "Air Koryo" },
	{ "iata": "WJ", "airline": "Air Labrador" },
	{ "iata": "7Q", "airline": "Air Libya" },
	{ "iata": "NX", "airline": "Air Macao" },
	{ "iata": "MD", "airline": "Air Madagascar" },
	{ "iata": "QM", "airline": "Air Malawi" },
	{ "iata": "XG", "airline": "Air Mali International" },
	{ "iata": "KM", "airline": "Air Malta" },
	{ "iata": "CW", "airline": "Air Marshall Islands" },
	{ "iata": "MK", "airline": "Air Mauritius" },
	{ "iata": "DR", "airline": "Air Mediterranee" },
	{ "iata": "MC", "airline": "Air Mobility Command" },
	{ "iata": "9U", "airline": "Air Moldova" },
	{ "iata": "SW", "airline": "Air Namibia" },
	{ "iata": "NZ", "airline": "Air Nelson" },
	{ "iata": "NZ", "airline": "Air New Zealand" },
	{ "iata": "7A", "airline": "Air Next" },
	{ "iata": "EL", "airline": "Air Nippon" },
	{ "iata": "EH", "airline": "Air Nippon Network Co. Ltd." },
	{ "iata": "PX", "airline": "Air Niugini" },
	{ "iata": "4N", "airline": "Air North" },
	{ "iata": "M3", "airline": "Air Norway" },
	{ "iata": "YW", "airline": "Air Nostrum" },
	{ "iata": "AP", "airline": "Air One" },
	{ "iata": "FJ", "airline": "Air Pacific" },
	{ "iata": "3D", "airline": "Air People International" },
	{ "iata": "2P", "airline": "Air Philippines" },
	{ "iata": "EB", "airline": "Air Pullmantur" },
	{ "iata": "PJ", "airline": "Air Saint Pierre" },
	{ "iata": "6O", "airline": "Air Satellite" },
	{ "iata": "V7", "airline": "Air Senegal International" },
	{ "iata": "G8", "airline": "Air Service Gabon" },
	{ "iata": "HM", "airline": "Air Seychelles" },
	{ "iata": "4D", "airline": "Air Sinai" },
	{ "iata": "GM", "airline": "Air Slovakia" },
	{ "iata": "WO", "airline": "Air Southwest" },
	{ "iata": "YI", "airline": "Air Sunshine" },
	{ "iata": "VT", "airline": "Air Tahiti" },
	{ "iata": "TN", "airline": "Air Tahiti Nui" },
	{ "iata": "TS", "airline": "Air Transat" },
	{ "iata": "8C", "airline": "Air Transport International LLC" },
	{ "iata": "JY", "airline": "Air Turks and Caicos" },
	{ "iata": "U7", "airline": "Air Uganda" },
	{ "iata": "3N", "airline": "Air Urga" },
	{ "iata": "VL", "airline": "Air VIA" },
	{ "iata": "DO", "airline": "Air Vallée" },
	{ "iata": "NF", "airline": "Air Vanuatu" },
	{ "iata": "ZW", "airline": "Air Wisconsin" },
	{ "iata": "ZT", "airline": "Air Zambezi" },
	{ "iata": "UM", "airline": "Air Zimbabwe" },
	{ "iata": "F8", "airline": "Air2there" },
	{ "iata": "AK", "airline": "AirAsia" },
	{ "iata": "D7", "airline": "AirAsia X" },
	{ "iata": "RU", "airline": "AirBridgeCargo Airlines" },
	{ "iata": "FL", "airline": "AirTran Airways" },
	{ "iata": "AP", "airline": "Airbus Industrie" },
	{ "iata": "SB", "airline": "Aircalin (Air Caledonie International)" },
	{ "iata": "4C", "airline": "Aires, Aerovias de Integracion Regional, S.A." },
	{ "iata": "P2", "airline": "Airkenya Express" },
	{ "iata": "A5", "airline": "Airlinair" },
	{ "iata": "FO", "airline": "Airlines Of Tasmania" },
	{ "iata": "CG", "airline": "Airlines PNG" },
	{ "iata": "4Z", "airline": "Airlink" },
	{ "iata": "TL", "airline": "Airnorth" },
	{ "iata": "PL", "airline": "Airstars" },
	{ "iata": "6L", "airline": "Aklak Air" },
	{ "iata": "2D", "airline": "Alania Airlines" },
	{ "iata": "AS", "airline": "Alaska Airlines" },
	{ "iata": "KO", "airline": "Alaska Central Express" },
	{ "iata": "LV", "airline": "Albanian Airlines" },
	{ "iata": "D4", "airline": "Alidaunia" },
	{ "iata": "AZ", "airline": "Alitalia" },
	{ "iata": "XM", "airline": "Alitalia Express" },
	{ "iata": "NH", "airline": "All Nippon Airways" },
	{ "iata": "G4", "airline": "Allegiant Air" },
	{ "iata": "LL", "airline": "Allegro" },
	{ "iata": "QQ", "airline": "Alliance Airlines" },
	{ "iata": "6T", "airline": "Almaty Aviation" },
	{ "iata": "KH", "airline": "Aloha Air Cargo" },
	{ "iata": "5A", "airline": "Alpine Air Express" },
	{ "iata": "6R", "airline": "Alrosa Mirny Air Enterprise" },
	{ "iata": "Z8", "airline": "Amaszonas" },
	{ "iata": "AA", "airline": "American Airlines" },
	{ "iata": "MQ", "airline": "American Eagle Airlines" },
	{ "iata": "A8", "airline": "Ameriflight" },
	{ "iata": "M6", "airline": "Amerijet International" },
	{ "iata": "WD", "airline": "Amsterdam Airlines" },
	{ "iata": "OY", "airline": "Andes Líneas Aéreas" },
	{ "iata": "8G", "airline": "Angel Airlines" },
	{ "iata": "5F", "airline": "Arctic Circle Air Service" },
	{ "iata": "ZE", "airline": "Arcus-Air Logistic" },
	{ "iata": "FG", "airline": "Ariana Afghan Airlines" },
	{ "iata": "W3", "airline": "Arik Air" },
	{ "iata": "OR", "airline": "Arkefly" },
	{ "iata": "IZ", "airline": "Arkia Israel Airlines" },
	{ "iata": "U8", "airline": "Armavia" },
	{ "iata": "JW", "airline": "Arrow Air" },
	{ "iata": "R7", "airline": "Aserca Airlines" },
	{ "iata": "HJ", "airline": "Asian Express Airlines" },
	{ "iata": "OZ", "airline": "Asiana Airlines" },
	{ "iata": "4K", "airline": "Askari Aviation" },
	{ "iata": "ER", "airline": "Astar Air Cargo" },
	{ "iata": "5W", "airline": "Astraeus" },
	{ "iata": "OB", "airline": "Astrakhan Airlines" },
	{ "iata": "8V", "airline": "Astral Aviation" },
	{ "iata": "3G", "airline": "Atlant-Soyuz Airlines" },
	{ "iata": "ZF", "airline": "Atlantic Airlines de Honduras" },
	{ "iata": "RC", "airline": "Atlantic Airways" },
	{ "iata": "EV", "airline": "Atlantic Southeast Airlines" },
	{ "iata": "TD", "airline": "Atlantis European Airways" },
	{ "iata": "5Y", "airline": "Atlas Air" },
	{ "iata": "8A", "airline": "Atlas Blue" },
	{ "iata": "KK", "airline": "Atlasjet" },
	{ "iata": "IP", "airline": "Atyrau Air Ways" },
	{ "iata": "IQ", "airline": "Augsburg Airways GmbH" },
	{ "iata": "GR", "airline": "Aurigny Air Services" },
	{ "iata": "AU", "airline": "Austral Lineas Aereas" },
	{ "iata": "XM", "airline": "Australian air Express" },
	{ "iata": "OS", "airline": "Austrian Airlines" },
	{ "iata": "VO", "airline": "Austrian Arrows (Tyrolean Airways)" },
	{ "iata": "TF", "airline": "Avia Traffic Company" },
	{ "iata": "ZR", "airline": "Aviacon Zitotrans" },
	{ "iata": "6A", "airline": "Aviacsa" },
	{ "iata": "7U", "airline": "Aviaenergo" },
	{ "iata": "EC", "airline": "Avialeasing Aviation Company" },
	{ "iata": "AV", "airline": "Avianca - Aerovias Nacionales de Colombia" },
	{ "iata": "4B", "airline": "Aviastar-TU" },
	{ "iata": "Z3", "airline": "Avient Aviation" },
	{ "iata": "U3", "airline": "Avies" },
	{ "iata": "JJ", "airline": "Aviogenex" },
	{ "iata": "9V", "airline": "Avior Airlines" },
	{ "iata": "G2", "airline": "Avirex" },
	{ "iata": "2Q", "airline": "Avitrans" },
	{ "iata": "6V", "airline": "Axis Airways" },
	{ "iata": "J2", "airline": "Azerbaijan Airlines" },
	{ "iata": "AD", "airline": "Azul Brazilian Airlines" },
	{ "iata": "JA", "airline": "B&H Airlines" },
	{ "iata": "CJ", "airline": "BA CityFlyer" },
	{ "iata": "B4", "airline": "BACH Flugbetriebsgesellschaft mbH" },
	{ "iata": "1B", "airline": "BH Air (Balkan Holidays)" },
	{ "iata": "BD", "airline": "BMI Regional" },
	{ "iata": "UP", "airline": "Bahamasair" },
	{ "iata": "2B", "airline": "Bahrain Air" },
	{ "iata": "PG", "airline": "Bangkok Airways" },
	{ "iata": "B4", "airline": "Bankair" },
	{ "iata": "8N", "airline": "Barents AirLink" },
	{ "iata": "7P", "airline": "Batavia Air" },
	{ "iata": "JV", "airline": "Bearskin Lake Air Service" },
	{ "iata": "4T", "airline": "Belair Airlines" },
	{ "iata": "B2", "airline": "Belavia Belarusian Airlines" },
	{ "iata": "LZ", "airline": "Belle Air" },
	{ "iata": "B3", "airline": "Bellview Airlines" },
	{ "iata": "CH", "airline": "Bemidji Airlines" },
	{ "iata": "A8", "airline": "Benin Golf Air" },
	{ "iata": "8E", "airline": "Bering Air" },
	{ "iata": "J8", "airline": "Berjaya Air" },
	{ "iata": "5Q", "airline": "Best Air" },
	{ "iata": "T1", "airline": "Bestair" },
	{ "iata": "BG", "airline": "Biman Bangladesh Airlines" },
	{ "iata": "NT", "airline": "Binter Canarias" },
	{ "iata": "5Z", "airline": "Bismillah Airlines" },
	{ "iata": "0B", "airline": "Blue Air" },
	{ "iata": "BZ", "airline": "Blue Dart Aviation" },
	{ "iata": "SI", "airline": "Blue Islands" },
	{ "iata": "4Y", "airline": "Blue Line" },
	{ "iata": "BV", "airline": "Blue Panorama Airlines" },
	{ "iata": "QW", "airline": "Blue Wings" },
	{ "iata": "KF", "airline": "Blue1" },
	{ "iata": "BF", "airline": "Bluebird Cargo" },
	{ "iata": "B8", "airline": "Botir-Avia" },
	{ "iata": "K6", "airline": "Bravo Air Congo" },
	{ "iata": "FQ", "airline": "Brindabella Airlines" },
	{ "iata": "DB", "airline": "Brit Air" },
	{ "iata": "BA", "airline": "British Airways" },
	{ "iata": "BS", "airline": "British International Helicopters" },
	{ "iata": "SN", "airline": "Brussels Airlines" },
	{ "iata": "J4", "airline": "Buffalo Airways" },
	{ "iata": "FB", "airline": "Bulgaria Air" },
	{ "iata": "1T", "airline": "Bulgarian Air Charter" },
	{ "iata": "UZ", "airline": "Buraq Air" },
	{ "iata": "4P", "airline": "Business Aviation" },
	{ "iata": "5C", "airline": "CAL Cargo Air Lines" },
	{ "iata": "XK", "airline": "CCM Airlines" },
	{ "iata": "AW", "airline": "CHC Airways" },
	{ "iata": "L5", "airline": "CHC Helikopter Service" },
	{ "iata": "MO", "airline": "Calm Air" },
	{ "iata": "C6", "airline": "CanJet" },
	{ "iata": "5T", "airline": "Canadian North" },
	{ "iata": "9K", "airline": "Cape Air" },
	{ "iata": "PT", "airline": "Capital Cargo International Airlines" },
	{ "iata": "BB", "airline": "Cargo B Airlines" },
	{ "iata": "8L", "airline": "Cargo Plus Aviation" },
	{ "iata": "2G", "airline": "Cargoitalia" },
	{ "iata": "W8", "airline": "Cargojet Airways" },
	{ "iata": "CV", "airline": "Cargolux" },
	{ "iata": "B9", "airline": "Caribair" },
	{ "iata": "BW", "airline": "Caribbean Airlines" },
	{ "iata": "V3", "airline": "Carpatair" },
	{ "iata": "RV", "airline": "Caspian Airlines" },
	{ "iata": "CX", "airline": "Cathay Pacific" },
	{ "iata": "KX", "airline": "Cayman Airways" },
	{ "iata": "5J", "airline": "Cebu Pacific" },
	{ "iata": "9M", "airline": "Central Mountain Air" },
	{ "iata": "C0", "airline": "Centralwings" },
	{ "iata": "J7", "airline": "Centre-Avia" },
	{ "iata": "WE", "airline": "Centurion Air Cargo" },
	{ "iata": "3U", "airline": "Chanchangi Airlines" },
	{ "iata": "2Z", "airline": "Chang\'an Airlines" },
	{ "iata": "RP", "airline": "Chautauqua Airlines" },
	{ "iata": "CI", "airline": "China Airlines" },
	{ "iata": "CK", "airline": "China Cargo Airlines" },
	{ "iata": "MU", "airline": "China Eastern Airlines" },
	{ "iata": "8Y", "airline": "China Postal Airlines" },
	{ "iata": "CZ", "airline": "China Southern Airlines" },
	{ "iata": "HR", "airline": "China United Airlines" },
	{ "iata": "PN", "airline": "China West Air" },
	{ "iata": "XO", "airline": "China Xinhua Airlines" },
	{ "iata": "OQ", "airline": "Chongqing Airlines" },
	{ "iata": "A2", "airline": "Cielos Airlines" },
	{ "iata": "QI", "airline": "Cimber Air" },
	{ "iata": "C9", "airline": "Cirrus Airlines" },
	{ "iata": "CF", "airline": "City Airline" },
	{ "iata": "G3", "airline": "City Connexion Airlines" },
	{ "iata": "WX", "airline": "CityJet" },
	{ "iata": "4C", "airline": "Click Airways" },
	{ "iata": "XG", "airline": "Clickair" },
	{ "iata": "9L", "airline": "Colgan Air" },
	{ "iata": "MN", "airline": "Comair" },
	{ "iata": "OH", "airline": "Comair" },
	{ "iata": "C5", "airline": "CommutAir" },
	{ "iata": "KR", "airline": "Comores Aviation" },
	{ "iata": "E9", "airline": "Compagnie Africaine d\'Aviation" },
	{ "iata": "I5", "airline": "Compagnie Aérienne du Mali" },
	{ "iata": "CP", "airline": "Compass Airlines" },
	{ "iata": "DE", "airline": "Condor Flugdienst" },
	{ "iata": "C3", "airline": "Contact Air" },
	{ "iata": "CO", "airline": "Continental Airlines" },
	{ "iata": "PC", "airline": "Continental Airways" },
	{ "iata": "CS", "airline": "Continental Micronesia" },
	{ "iata": "V0", "airline": "Conviasa" },
	{ "iata": "CM", "airline": "Copa Airlines" },
	{ "iata": "SS", "airline": "Corsairfly" },
	{ "iata": "F5", "airline": "Cosmic Air" },
	{ "iata": "7C", "airline": "Coyne Aviation" },
	{ "iata": "OU", "airline": "Croatia Airlines" },
	{ "iata": "CU", "airline": "Cubana de Aviacion" },
	{ "iata": "5R", "airline": "Custom Air Transport" },
	{ "iata": "CY", "airline": "Cyprus Airways" },
	{ "iata": "KY", "airline": "Cyprus Turkish Airlines (KTHY Kibris Turk Hava Yollari)" },
	{ "iata": "OK", "airline": "Czech Airlines" },
	{ "iata": "DX", "airline": "DAT Danish Air Transport" },
	{ "iata": "D5", "airline": "DHL Aero Expreso" },
	{ "iata": "D0", "airline": "DHL Air UK" },
	{ "iata": "ES", "airline": "DHL International Aviation ME" },
	{ "iata": "L3", "airline": "DHL de Guatemala" },
	{ "iata": "R6", "airline": "DOT LT" },
	{ "iata": "1I", "airline": "DRF Luftrettung" },
	{ "iata": "D3", "airline": "Daallo Airlines" },
	{ "iata": "N2", "airline": "Dagestan Airlines" },
	{ "iata": "0D", "airline": "Darwin Airline" },
	{ "iata": "JD", "airline": "Deer Jet" },
	{ "iata": "DL", "airline": "Delta Air Lines" },
	{ "iata": "3D", "airline": "Denim Air" },
	{ "iata": "HS", "airline": "Direktflyg" },
	{ "iata": "AW", "airline": "Dirgantara Air Service" },
	{ "iata": "D8", "airline": "Djibouti Airlines" },
	{ "iata": "Z6", "airline": "Dniproavia" },
	{ "iata": "ZD", "airline": "Dolphin Air" },
	{ "iata": "5D", "airline": "DonbassAero" },
	{ "iata": "KA", "airline": "Dragonair, Hong Kong Dragon Airlines" },
	{ "iata": "KB", "airline": "Druk Air" },
	{ "iata": "9H", "airline": "Dutch Antilles Express" },
	{ "iata": "BR", "airline": "EVA Air" },
	{ "iata": "H7", "airline": "Eagle Air" },
	{ "iata": "NZ", "airline": "Eagle Airways" },
	{ "iata": "QU", "airline": "East African" },
	{ "iata": "S9", "airline": "East African Safari Air Express" },
	{ "iata": "8C", "airline": "East Star Air" },
	{ "iata": "T3", "airline": "Eastern Airways" },
	{ "iata": "QF", "airline": "Eastern Australia Airlines" },
	{ "iata": "EF", "airline": "EasyFly" },
	{ "iata": "8Y", "airline": "Ecuato Guineana" },
	{ "iata": "WK", "airline": "Edelweiss Air" },
	{ "iata": "MS", "airline": "EgyptAir Cargo" },
	{ "iata": "MS", "airline": "EgyptAir Express" },
	{ "iata": "MS", "airline": "Egyptair" },
	{ "iata": "LY", "airline": "El Al Israel Airlines" },
	{ "iata": "EK", "airline": "Emirates Airline" },
	{ "iata": "EM", "airline": "Empire Airlines" },
	{ "iata": "EU", "airline": "Empresa Ecuatoriana De Aviacion" },
	{ "iata": "G8", "airline": "Enkor" },
	{ "iata": "7H", "airline": "Era Aviation" },
	{ "iata": "B8", "airline": "Eritrean Airlines" },
	{ "iata": "E7", "airline": "Estafeta Carga Aerea" },
	{ "iata": "OV", "airline": "Estonian Air" },
	{ "iata": "ET", "airline": "Ethiopian Airlines" },
	{ "iata": "EY", "airline": "Etihad Airways" },
	{ "iata": "5B", "airline": "Euro-Asia Air" },
	{ "iata": "6M", "airline": "EuroAir" },
	{ "iata": "UI", "airline": "Eurocypria Airlines" },
	{ "iata": "GJ", "airline": "Eurofly" },
	{ "iata": "K2", "airline": "Eurolot" },
	{ "iata": "5O", "airline": "Europe Airpost" },
	{ "iata": "QY", "airline": "European Air Transport" },
	{ "iata": "EW", "airline": "Eurowings" },
	{ "iata": "EZ", "airline": "Evergreen International Airlines" },
	{ "iata": "3Z", "airline": "Everts Air Cargo" },
	{ "iata": "OW", "airline": "Executive Airlines" },
	{ "iata": "8D", "airline": "Expo Aviation" },
	{ "iata": "EO", "airline": "Express One International" },
	{ "iata": "XE", "airline": "ExpressJet Airlines" },
	{ "iata": "ZY", "airline": "Eznis Airways" },
	{ "iata": "4A", "airline": "FS Air Service" },
	{ "iata": "F3", "airline": "Faso Airways" },
	{ "iata": "FX", "airline": "FedEx Express" },
	{ "iata": "AY", "airline": "Finnair" },
	{ "iata": "FC", "airline": "Finncomm Airlines" },
	{ "iata": "FY", "airline": "Firefly" },
	{ "iata": "7F", "airline": "First Air" },
	{ "iata": "JH", "airline": "Flex Linhas Aéreas" },
	{ "iata": "4Y", "airline": "Flight Alaska" },
	{ "iata": "RF", "airline": "Florida West International Airways" },
	{ "iata": "6P", "airline": "Fly Wex" },
	{ "iata": "5H", "airline": "Fly540" },
	{ "iata": "TE", "airline": "FlyLal (Lithuanian Airlines)" },
	{ "iata": "F7", "airline": "Flybaboo" },
	{ "iata": "BE", "airline": "Flybe" },
	{ "iata": "B4", "airline": "Flyglobespan" },
	{ "iata": "7Y", "airline": "Flying Carpet" },
	{ "iata": "HK", "airline": "Four Star Aviation / Four Star Cargo" },
	{ "iata": "XD", "airline": "Freebird Airlines" },
	{ "iata": "FP", "airline": "Freedom Air" },
	{ "iata": "F8", "airline": "Freedom Airlines" },
	{ "iata": "F9", "airline": "Frontier Airlines" },
	{ "iata": "2F", "airline": "Frontier Flying Service" },
	{ "iata": "GY", "airline": "Gabon Airlines" },
	{ "iata": "GP", "airline": "Gadair European Airlines" },
	{ "iata": "7O", "airline": "Galaxy Air" },
	{ "iata": "GA", "airline": "Garuda Indonesia" },
	{ "iata": "4G", "airline": "Gazpromavia" },
	{ "iata": "A9", "airline": "Georgian Airways" },
	{ "iata": "QB", "airline": "Georgian National Airlines" },
	{ "iata": "ST", "airline": "Germania" },
	{ "iata": "4U", "airline": "Germanwings" },
	{ "iata": "GP", "airline": "Gestair" },
	{ "iata": "G0", "airline": "Ghana International Airlines" },
	{ "iata": "XH", "airline": "Global Supply Systems" },
	{ "iata": "G8", "airline": "GoAir" },
	{ "iata": "G7", "airline": "GoJet Airlines" },
	{ "iata": "G3", "airline": "Gol Transportes Aéreos" },
	{ "iata": "DC", "airline": "Golden Air" },
	{ "iata": "YD", "airline": "Gomelavia" },
	{ "iata": "G1", "airline": "Gorkha Airlines" },
	{ "iata": "YR", "airline": "Grand Canyon Airlines" },
	{ "iata": "GS", "airline": "Grand China Express Air" },
	{ "iata": "GS", "airline": "Grant Aviation" },
	{ "iata": "ZK", "airline": "Great Lakes Airlines" },
	{ "iata": "IJ", "airline": "Great Wall Airlines" },
	{ "iata": "G6", "airline": "Guine Bissaur Airlines" },
	{ "iata": "J9", "airline": "Guinee Airlines" },
	{ "iata": "GF", "airline": "Gulf Air Bahrain" },
	{ "iata": "3M", "airline": "Gulfstream International Airlines" },
	{ "iata": "H6", "airline": "Hageland Aviation Services" },
	{ "iata": "HR", "airline": "Hahn Air" },
	{ "iata": "HU", "airline": "Hainan Airlines" },
	{ "iata": "4R", "airline": "Hamburg International" },
	{ "iata": "HA", "airline": "Hawaiian Airlines" },
	{ "iata": "HN", "airline": "Heavylift Cargo Airlines" },
	{ "iata": "YO", "airline": "Heli Air Monaco" },
	{ "iata": "JB", "airline": "Helijet" },
	{ "iata": "T4", "airline": "Hellas Jet" },
	{ "iata": "HT", "airline": "Hellenic Imperial Airways" },
	{ "iata": "HW", "airline": "Hello" },
	{ "iata": "2L", "airline": "Helvetic Airways" },
	{ "iata": "DU", "airline": "Hemus Air" },
	{ "iata": "EO", "airline": "Hewa Bora Airways" },
	{ "iata": "UD", "airline": "Hex\'Air" },
	{ "iata": "5K", "airline": "Hi Fly" },
	{ "iata": "8H", "airline": "Highland Airways" },
	{ "iata": "HD", "airline": "Hokkaido International Airlines" },
	{ "iata": "H5", "airline": "Hola Airlines" },
	{ "iata": "N8", "airline": "Hong Kong Airlines" },
	{ "iata": "UO", "airline": "Hong Kong Express Airways" },
	{ "iata": "QX", "airline": "Horizon Air" },
	{ "iata": "II", "airline": "IBC Airways" },
	{ "iata": "IB", "airline": "Iberia Airlines" },
	{ "iata": "TY", "airline": "Iberworld" },
	{ "iata": "FW", "airline": "Ibex Airlines" },
	{ "iata": "X8", "airline": "Icaro Air" },
	{ "iata": "FI", "airline": "Icelandair" },
	{ "iata": "IK", "airline": "Imair Airlines" },
	{ "iata": "6E", "airline": "IndiGo Airlines" },
	{ "iata": "I8", "airline": "Indonesia Air Transport" },
	{ "iata": "QZ", "airline": "Indonesia AirAsia" },
	{ "iata": "7I", "airline": "Insel Air" },
	{ "iata": "3L", "airline": "InterSky" },
	{ "iata": "D6", "airline": "Interair South Africa" },
	{ "iata": "4O", "airline": "Interjet" },
	{ "iata": "ID", "airline": "Interlink Airlines" },
	{ "iata": "6I", "airline": "International Business Air" },
	{ "iata": "I4", "airline": "Interstate Airline" },
	{ "iata": "IR", "airline": "Iran Air" },
	{ "iata": "B9", "airline": "Iran Air Tours" },
	{ "iata": "EP", "airline": "Iran Aseman Airlines" },
	{ "iata": "IA", "airline": "Iraqi Airways" },
	{ "iata": "WP", "airline": "Island Air" },
	{ "iata": "2S", "airline": "Island Express" },
	{ "iata": "IF", "airline": "Islas Airways" },
	{ "iata": "WC", "airline": "Islena De Inversiones" },
	{ "iata": "5Y", "airline": "Isles of Scilly Skybus" },
	{ "iata": "6H", "airline": "Israir Airlines" },
	{ "iata": "9X", "airline": "ItAli Airlines" },
	{ "iata": "GI", "airline": "Itek Air" },
	{ "iata": "H9", "airline": "Izair" },
	{ "iata": "XM", "airline": "J-Air" },
	{ "iata": "JC", "airline": "JAL Express" },
	{ "iata": "JO", "airline": "JALways" },
	{ "iata": "JI", "airline": "Jade Cargo International" },
	{ "iata": "3X", "airline": "Japan Air Commuter" },
	{ "iata": "JL", "airline": "Japan Airlines" },
	{ "iata": "NU", "airline": "Japan Transocean Air" },
	{ "iata": "JU", "airline": "Jat Airways" },
	{ "iata": "J9", "airline": "Jazeera Airways" },
	{ "iata": "7C", "airline": "Jeju Air" },
	{ "iata": "O2", "airline": "Jet Air" },
	{ "iata": "9W", "airline": "Jet Airways" },
	{ "iata": "PP", "airline": "Jet Aviation" },
	{ "iata": "LS", "airline": "Jet2.com" },
	{ "iata": "8J", "airline": "Jet4you" },
	{ "iata": "B6", "airline": "JetBlue Airways" },
	{ "iata": "QF", "airline": "JetConnect" },
	{ "iata": "S2", "airline": "JetLite" },
	{ "iata": "JF", "airline": "Jetairfly" },
	{ "iata": "0J", "airline": "Jetclub" },
	{ "iata": "JQ", "airline": "Jetstar Airways" },
	{ "iata": "3K", "airline": "Jetstar Asia Airways" },
	{ "iata": "BL", "airline": "Jetstar Pacific" },
	{ "iata": "JX", "airline": "Jett8 Airlines Cargo" },
	{ "iata": "LJ", "airline": "Jin Air" },
	{ "iata": "R5", "airline": "Jordan Aviation" },
	{ "iata": "6J", "airline": "Jubba Airways" },
	{ "iata": "HO", "airline": "Juneyao Airlines" },
	{ "iata": "XC", "airline": "KD Air" },
	{ "iata": "KD", "airline": "KD Avia" },
	{ "iata": "WA", "airline": "KLM Cityhopper" },
	{ "iata": "KL", "airline": "KLM Royal Dutch Airlines" },
	{ "iata": "N2", "airline": "Kabo Air" },
	{ "iata": "K4", "airline": "Kalitta Air" },
	{ "iata": "K9", "airline": "Kalitta Charters" },
	{ "iata": "RQ", "airline": "Kam Air" },
	{ "iata": "E2", "airline": "Kampuchea Airlines" },
	{ "iata": "5R", "airline": "Karthago Airlines" },
	{ "iata": "3Y", "airline": "Kartika Airlines" },
	{ "iata": "KV", "airline": "Kavminvodyavia" },
	{ "iata": "KW", "airline": "Kelowna Flightcraft Air Charter" },
	{ "iata": "M5", "airline": "Kenmore Air" },
	{ "iata": "4K", "airline": "Kenn Borek Air" },
	{ "iata": "KQ", "airline": "Kenya Airways" },
	{ "iata": "BZ", "airline": "Keystone Air Services" },
	{ "iata": "X9", "airline": "Khors Aircompany" },
	{ "iata": "IT", "airline": "Kingfisher Airlines" },
	{ "iata": "DN", "airline": "Kingfisher Red" },
	{ "iata": "Y9", "airline": "Kish Air" },
	{ "iata": "7K", "airline": "Kogalymavia" },
	{ "iata": "K7", "airline": "KoralBlue Airlines" },
	{ "iata": "KE", "airline": "Korean Air" },
	{ "iata": "GW", "airline": "Kuban Airlines" },
	{ "iata": "VD", "airline": "Kunpeng Airlines" },
	{ "iata": "KU", "airline": "Kuwait Airways" },
	{ "iata": "GO", "airline": "Kuzu Airlines Cargo" },
	{ "iata": "QH", "airline": "Kyrgyzstan" },
	{ "iata": "R8", "airline": "Kyrgyzstan Airlines" },
	{ "iata": "A0", "airline": "L\'Avion" },
	{ "iata": "JF", "airline": "L.A.B. Flying Service" },
	{ "iata": "LR", "airline": "LACSA" },
	{ "iata": "5U", "airline": "LADE - Líneas Aéreas del Estado" },
	{ "iata": "KG", "airline": "LAI - Linea Aerea IAACA" },
	{ "iata": "LM", "airline": "LAM Mozambique Airlines" },
	{ "iata": "LA", "airline": "LAN Airlines" },
	{ "iata": "4M", "airline": "LAN Argentina" },
	{ "iata": "UC", "airline": "LAN Cargo" },
	{ "iata": "XL", "airline": "LAN Ecuador" },
	{ "iata": "LU", "airline": "LAN Express" },
	{ "iata": "LP", "airline": "LAN Peru" },
	{ "iata": "8z", "airline": "LASER Airlines" },
	{ "iata": "LO", "airline": "LOT Polish Airlines" },
	{ "iata": "LT", "airline": "LTU International" },
	{ "iata": "IK", "airline": "Lankair" },
	{ "iata": "QV", "airline": "Lao Airlines" },
	{ "iata": "NG", "airline": "Lauda Air" },
	{ "iata": "LI", "airline": "Leeward Islands Air Transport" },
	{ "iata": "LN", "airline": "Libyan Airlines" },
	{ "iata": "6V", "airline": "Lignes Aériennes Congolaises" },
	{ "iata": "LD", "airline": "Linea Turistica Aerotuy" },
	{ "iata": "JT", "airline": "Lion Air (Lion Mentari Airlines )" },
	{ "iata": "LM", "airline": "Livingston Energy Flight" },
	{ "iata": "LC", "airline": "Loganair" },
	{ "iata": "T2", "airline": "Lotus Air" },
	{ "iata": "8L", "airline": "Lucky Air" },
	{ "iata": "HE", "airline": "Luftfahrtgesellschaft Walter" },
	{ "iata": "LH", "airline": "Lufthansa" },
	{ "iata": "LH", "airline": "Lufthansa Cargo" },
	{ "iata": "CL", "airline": "Lufthansa CityLine" },
	{ "iata": "DV", "airline": "Lufttaxi Fluggesellschaft" },
	{ "iata": "L5", "airline": "Lufttransport" },
	{ "iata": "LG", "airline": "Luxair" },
	{ "iata": "5V", "airline": "Lviv Airlines" },
	{ "iata": "L2", "airline": "Lynden Air Cargo" },
	{ "iata": "L4", "airline": "Lynx Aviation" },
	{ "iata": "MH", "airline": "MASkargo (Malaysia Airlines Kargo)" },
	{ "iata": "MH", "airline": "MASwings" },
	{ "iata": "IN", "airline": "MAT Macedonian Airlines" },
	{ "iata": "OM", "airline": "MIAT Mongolian Airlines" },
	{ "iata": "7G", "airline": "MK Airlines" },
	{ "iata": "MB", "airline": "MNG Airlines" },
	{ "iata": "CC", "airline": "Macair Airlines" },
	{ "iata": "UJ", "airline": "Magnicharters" },
	{ "iata": "W5", "airline": "Mahan Air" },
	{ "iata": "MH", "airline": "Malaysia Airlines" },
	{ "iata": "Q2", "airline": "Maldivian" },
	{ "iata": "MV", "airline": "Maldivian Air Taxi" },
	{ "iata": "MA", "airline": "Malev Hungarian Airlines" },
	{ "iata": "Z8", "airline": "Mali Airways" },
	{ "iata": "TF", "airline": "Malmö Aviation" },
	{ "iata": "RI", "airline": "Mandala Airlines" },
	{ "iata": "AE", "airline": "Mandarin Airlines" },
	{ "iata": "JE", "airline": "Mango" },
	{ "iata": "6V", "airline": "Mars RK" },
	{ "iata": "M7", "airline": "Marsland Aviation" },
	{ "iata": "MP", "airline": "Martinair" },
	{ "iata": "M7", "airline": "MasAir" },
	{ "iata": "L6", "airline": "Mauritania Airlines International" },
	{ "iata": "8M", "airline": "Maxair" },
	{ "iata": "MW", "airline": "Maya Island Air" },
	{ "iata": "N5", "airline": "Medavia" },
	{ "iata": "IM", "airline": "Menajet" },
	{ "iata": "IG", "airline": "Meridiana" },
	{ "iata": "MZ", "airline": "Merpati Nusantara Airlines" },
	{ "iata": "YV", "airline": "Mesa Airlines" },
	{ "iata": "XJ", "airline": "Mesaba Airlines" },
	{ "iata": "MX", "airline": "Mexicana" },
	{ "iata": "QA", "airline": "MexicanaClick" },
	{ "iata": "GL", "airline": "Miami Air International" },
	{ "iata": "7Y", "airline": "Mid Airlines" },
	{ "iata": "ME", "airline": "Middle East Airlines" },
	{ "iata": "JI", "airline": "Midway Airlines" },
	{ "iata": "MY", "airline": "Midwest Airlines" },
	{ "iata": "MJ", "airline": "Mihin Lanka" },
	{ "iata": "MW", "airline": "Mokulele Airlines" },
	{ "iata": "2M", "airline": "Moldavian Airlines" },
	{ "iata": "ZB", "airline": "Monarch Airlines" },
	{ "iata": "YM", "airline": "Montenegro Airlines" },
	{ "iata": "3R", "airline": "Moskovia Airlines" },
	{ "iata": "M9", "airline": "Motor Sich" },
	{ "iata": "NM", "airline": "Mount Cook Airlines" },
	{ "iata": "8I", "airline": "MyAir" },
	{ "iata": "UB", "airline": "Myanma Airways" },
	{ "iata": "8M", "airline": "Myanmar Airways International" },
	{ "iata": "DV", "airline": "Nantucket Airlines" },
	{ "iata": "XY", "airline": "Nas Air" },
	{ "iata": "UE", "airline": "Nasair" },
	{ "iata": "5M", "airline": "National Airlines" },
	{ "iata": "YJ", "airline": "National Airways" },
	{ "iata": "NC", "airline": "National Jet Systems" },
	{ "iata": "5C", "airline": "Nature Air" },
	{ "iata": "ON", "airline": "Nauru Air Corporation" },
	{ "iata": "ZN", "airline": "Navegacion y Servicios Aéreos Canarios (NAYSA)" },
	{ "iata": "NO", "airline": "Neos" },
	{ "iata": "RA", "airline": "Nepal Airlines" },
	{ "iata": "1I", "airline": "NetJets" },
	{ "iata": "1I", "airline": "NetJets Europe" },
	{ "iata": "EJ", "airline": "New England Airlines" },
	{ "iata": "2N", "airline": "Nextjet" },
	{ "iata": "HG", "airline": "Niki" },
	{ "iata": "KZ", "airline": "Nippon Cargo Airlines" },
	{ "iata": "DD", "airline": "Nok Air" },
	{ "iata": "6N", "airline": "Nordic Airways" },
	{ "iata": "6N", "airline": "Nordic Regional" },
	{ "iata": "NA", "airline": "North American Airlines" },
	{ "iata": "M3", "airline": "North Flying" },
	{ "iata": "HW", "airline": "North-Wright Airways" },
	{ "iata": "NC", "airline": "Northern Air Cargo" },
	{ "iata": "NW", "airline": "Northwest Airlines" },
	{ "iata": "FY", "airline": "Northwest Regional Airlines" },
	{ "iata": "J3", "airline": "Northwestern Air" },
	{ "iata": "DY", "airline": "Norwegian Air Shuttle" },
	{ "iata": "BJ", "airline": "Nouvelair" },
	{ "iata": "M4", "airline": "Nova Airline" },
	{ "iata": "1I", "airline": "Novair" },
	{ "iata": "OL", "airline": "OLT - Ostfriesische Lufttransport" },
	{ "iata": "O6", "airline": "Oceanair" },
	{ "iata": "5K", "airline": "Odessa Airlines" },
	{ "iata": "BK", "airline": "Okay Airways" },
	{ "iata": "OA", "airline": "Olympic Airlines" },
	{ "iata": "WY", "airline": "Oman Air" },
	{ "iata": "OY", "airline": "Omni Air International" },
	{ "iata": "OX", "airline": "One-Two-GO Airlines" },
	{ "iata": "8Q", "airline": "Onur Air" },
	{ "iata": "EC", "airline": "OpenSkies" },
	{ "iata": "R2", "airline": "Orenair (Orenburg Airlines)" },
	{ "iata": "OX", "airline": "Orient Thai Airlines" },
	{ "iata": "OJ", "airline": "Overland Airways" },
	{ "iata": "O7", "airline": "Ozjet Airlines" },
	{ "iata": "PV", "airline": "PAN Air" },
	{ "iata": "9Q", "airline": "PB Air" },
	{ "iata": "PU", "airline": "PLUNA" },
	{ "iata": "U4", "airline": "PMTair" },
	{ "iata": "US", "airline": "PSA Airlines" },
	{ "iata": "Y5", "airline": "Pace Airlines" },
	{ "iata": "DJ", "airline": "Pacific Blue Airlines" },
	{ "iata": "8P", "airline": "Pacific Coastal Airline" },
	{ "iata": "Q8", "airline": "Pacific East Asia Cargo Airlines" },
	{ "iata": "LW", "airline": "Pacific Wings" },
	{ "iata": "PK", "airline": "Pakistan International Airlines" },
	{ "iata": "PF", "airline": "Palestinian Airlines" },
	{ "iata": "NR", "airline": "Pamir Airways" },
	{ "iata": "PQ", "airline": "Panafrican Airways" },
	{ "iata": "P8", "airline": "Pantanal Linhas Aereas Sul-Matogrossenses" },
	{ "iata": "I7", "airline": "Paramount Airways" },
	{ "iata": "2F", "airline": "Payam Air" },
	{ "iata": "HP", "airline": "Pearl Airways" },
	{ "iata": "H9", "airline": "Pegasus Airlines" },
	{ "iata": "7V", "airline": "Pelican Air Services" },
	{ "iata": "6D", "airline": "Pelita Air Service" },
	{ "iata": "KS", "airline": "PenAir (Peninsula Airways)" },
	{ "iata": "PE", "airline": "People\'s Viennaline" },
	{ "iata": "4B", "airline": "Perimeter Aviation (Perimeter Airlines)" },
	{ "iata": "P9", "airline": "Perm Airlines" },
	{ "iata": "PR", "airline": "Philippine Airlines" },
	{ "iata": "9R", "airline": "Phuket Air" },
	{ "iata": "PI", "airline": "Piedmont Airlines" },
	{ "iata": "9E", "airline": "Pinnacle Airlines" },
	{ "iata": "PO", "airline": "Polar Air Cargo" },
	{ "iata": "YQ", "airline": "Polet Airlines" },
	{ "iata": "PH", "airline": "Polynesian Airlines" },
	{ "iata": "PD", "airline": "Porter Airlines" },
	{ "iata": "NI", "airline": "Portugalia" },
	{ "iata": "PW", "airline": "Precision Air" },
	{ "iata": "TO", "airline": "President Airlines" },
	{ "iata": "GX", "airline": "Primera Air" },
	{ "iata": "8W", "airline": "Private Wings Flugcharter" },
	{ "iata": "PB", "airline": "Provincial Airlines" },
	{ "iata": "QF", "airline": "Qantas" },
	{ "iata": "QR", "airline": "Qatar Airways" },
	{ "iata": "RT", "airline": "RAK Airways" },
	{ "iata": "WZ", "airline": "Red Wings Airlines" },
	{ "iata": "8L", "airline": "Redhill Aviation" },
	{ "iata": "FN", "airline": "Regional Air Lines" },
	{ "iata": "YS", "airline": "Regional Compagnie Aerienne Europeenne" },
	{ "iata": "ZL", "airline": "Regional Express Airlines" },
	{ "iata": "RW", "airline": "Republic Airlines" },
	{ "iata": "RH", "airline": "Republic Express Airlines" },
	{ "iata": "PK", "airline": "Riau Airlines" },
	{ "iata": "C7", "airline": "Rico Linhas Aereas" },
	{ "iata": "WQ", "airline": "Romavia" },
	{ "iata": "FV", "airline": "Rossiya - Russian Airlines" },
	{ "iata": "RR", "airline": "Royal Air Force" },
	{ "iata": "RS", "airline": "Royal Air Force of Oman" },
	{ "iata": "AT", "airline": "Royal Air Maroc" },
	{ "iata": "R0", "airline": "Royal Airlines" },
	{ "iata": "BI", "airline": "Royal Brunei Airlines" },
	{ "iata": "6D", "airline": "Royal Daisy Airlines" },
	{ "iata": "RJ", "airline": "Royal Jordanian" },
	{ "iata": "RK", "airline": "Royal Khmer Airlines" },
	{ "iata": "RL", "airline": "Royal Phnom Penh Airways" },
	{ "iata": "P7", "airline": "Russian Sky Airlines" },
	{ "iata": "WB", "airline": "Rwandair Express" },
	{ "iata": "RD", "airline": "Ryan International Airlines" },
	{ "iata": "FR", "airline": "Ryanair" },
	{ "iata": "S7", "airline": "S7 Airlines (Siberia Airlines)" },
	{ "iata": "MM", "airline": "SAM Colombia" },
	{ "iata": "HZ", "airline": "SAT Airlines" },
	{ "iata": "SP", "airline": "SATA Air Acores" },
	{ "iata": "S4", "airline": "SATA International" },
	{ "iata": "9N", "airline": "SATENA" },
	{ "iata": "5E", "airline": "SGA Airlines" },
	{ "iata": "SA", "airline": "Sabah Air" },
	{ "iata": "FA", "airline": "Safair" },
	{ "iata": "PV", "airline": "Saint Barth Commuter" },
	{ "iata": "ZS", "airline": "Sama Airlines" },
	{ "iata": "S3", "airline": "Santa Barbara Airlines" },
	{ "iata": "6W", "airline": "Saravia" },
	{ "iata": "HZ", "airline": "Sat Airlines" },
	{ "iata": "SV", "airline": "Saudi Arabian Airlines" },
	{ "iata": "W7", "airline": "Sayakhat Airlines" },
	{ "iata": "SK", "airline": "Scandinavian Airlines System (SAS)" },
	{ "iata": "DV", "airline": "Scat Aircompany" },
	{ "iata": "YR", "airline": "Scenic Airlines" },
	{ "iata": "CB", "airline": "ScotAirways" },
	{ "iata": "BB", "airline": "Seaborne Airlines" },
	{ "iata": "SJ", "airline": "Seagle Air" },
	{ "iata": "5S", "airline": "Servicios Aereos Profesionales" },
	{ "iata": "FS", "airline": "Servicios de Transportes Aereos Fueguinos" },
	{ "iata": "NL", "airline": "Shaheen Air International" },
	{ "iata": "SC", "airline": "Shandong Airlines" },
	{ "iata": "FM", "airline": "Shanghai Airlines" },
	{ "iata": "F4", "airline": "Shanghai Airlines Cargo" },
	{ "iata": "8C", "airline": "Shanxi Airlines" },
	{ "iata": "ZH", "airline": "Shenzhen Airlines" },
	{ "iata": "J5", "airline": "Shenzhen Donghai Airlines" },
	{ "iata": "S5", "airline": "Shuttle America" },
	{ "iata": "3U", "airline": "Sichuan Airlines" },
	{ "iata": "LJ", "airline": "Sierra National Airlines" },
	{ "iata": "SI", "airline": "Sierra Pacific Airlines" },
	{ "iata": "ZP", "airline": "Silk Way Airlines" },
	{ "iata": "MI", "airline": "SilkAir" },
	{ "iata": "SQ", "airline": "Singapore Airlines" },
	{ "iata": "SQ", "airline": "Singapore Airlines Cargo" },
	{ "iata": "H2", "airline": "Sky Airline" },
	{ "iata": "SY", "airline": "Sky Airlines" },
	{ "iata": "G3", "airline": "Sky Express" },
	{ "iata": "XW", "airline": "Sky Express" },
	{ "iata": "I6", "airline": "Sky Eyes" },
	{ "iata": "NE", "airline": "SkyEurope" },
	{ "iata": "OO", "airline": "SkyWest Airlines" },
	{ "iata": "BC", "airline": "Skymark Airlines" },
	{ "iata": "6J", "airline": "Skynet Asia Airways" },
	{ "iata": "5G", "airline": "Skyservice Airlines" },
	{ "iata": "NP", "airline": "Skytrans Airlines" },
	{ "iata": "KI", "airline": "Skyway Enterprises" },
	{ "iata": "JZ", "airline": "Skyways Express" },
	{ "iata": "XR", "airline": "Skywest Airlines" },
	{ "iata": "QS", "airline": "Smart Wings" },
	{ "iata": "6Y", "airline": "SmartLynx Airlines" },
	{ "iata": "DA", "airline": "Sol Dominicana Airlines" },
	{ "iata": "IE", "airline": "Solomon Airlines" },
	{ "iata": "SA", "airline": "South African Airways" },
	{ "iata": "YB", "airline": "South African Express" },
	{ "iata": "YG", "airline": "South Airlines" },
	{ "iata": "DG", "airline": "South East Asian Airlines" },
	{ "iata": "9S", "airline": "Southern Air" },
	{ "iata": "PL", "airline": "Southern Air Charter" },
	{ "iata": "WN", "airline": "Southwest Airlines" },
	{ "iata": "JK", "airline": "Spanair" },
	{ "iata": "SG", "airline": "Spicejet" },
	{ "iata": "NK", "airline": "Spirit Airlines" },
	{ "iata": "9S", "airline": "Spring Airlines" },
	{ "iata": "UL", "airline": "SriLankan Airlines" },
	{ "iata": "SJ", "airline": "Sriwijaya Air" },
	{ "iata": "S6", "airline": "Star Air" },
	{ "iata": "6S", "airline": "Star Air Aviation" },
	{ "iata": "7G", "airline": "Star Flyer" },
	{ "iata": "2I", "airline": "Star Perú" },
	{ "iata": "DZ", "airline": "Starline.kz" },
	{ "iata": "SD", "airline": "Sudan Airways" },
	{ "iata": "EZ", "airline": "Sun Air of Scandinavia" },
	{ "iata": "SY", "airline": "Sun Country Airlines" },
	{ "iata": "7L", "airline": "Sun d\'Or International Airlines" },
	{ "iata": "XQ", "airline": "SunExpress" },
	{ "iata": "CQ", "airline": "Sunshine Express Airlines" },
	{ "iata": "QF", "airline": "Sunstate Airlines" },
	{ "iata": "WG", "airline": "Sunwing Airlines" },
	{ "iata": "SO", "airline": "Superior Aviation" },
	{ "iata": "PY", "airline": "Surinam Airways" },
	{ "iata": "SA", "airline": "Swaziland Airlink" },
	{ "iata": "Q7", "airline": "Swift Air" },
	{ "iata": "W3", "airline": "Swiftair" },
	{ "iata": "LX", "airline": "Swiss European Air Lines" },
	{ "iata": "LX", "airline": "Swiss International Air Lines" },
	{ "iata": "7E", "airline": "Sylt Air" },
	{ "iata": "RB", "airline": "Syrian Arab Airlines (Syrianair)" },
	{ "iata": "DT", "airline": "TAAG Angola Airlines (Linhas Aéreas de Angola)" },
	{ "iata": "T0", "airline": "TACA Peru" },
	{ "iata": "VR", "airline": "TACV" },
	{ "iata": "VR", "airline": "TACV Cabo Verde Airlines" },
	{ "iata": "R9", "airline": "TAF Linhas Aéreas" },
	{ "iata": "PZ", "airline": "TAM Airlines" },
	{ "iata": "JJ", "airline": "TAM Airlines (TAM Linhas Aereas)" },
	{ "iata": "EQ", "airline": "TAME" },
	{ "iata": "TP", "airline": "TAP Portugal" },
	{ "iata": "3V", "airline": "TNT Airways" },
	{ "iata": "8R", "airline": "TRIP Linhas Aereas" },
	{ "iata": "X3", "airline": "TUIfly" },
	{ "iata": "6B", "airline": "TUIfly Nordic" },
	{ "iata": "7J", "airline": "Tajik Air" },
	{ "iata": "QT", "airline": "Tampa Cargo" },
	{ "iata": "TQ", "airline": "Tandem Aero" },
	{ "iata": "RO", "airline": "Tarom" },
	{ "iata": "SF", "airline": "Tassili Airlines" },
	{ "iata": "U9", "airline": "Tatarstan Airlines" },
	{ "iata": "T6", "airline": "Tavrey Airlines" },
	{ "iata": "L6", "airline": "Tbilaviamsheni" },
	{ "iata": "FD", "airline": "Thai AirAsia" },
	{ "iata": "TG", "airline": "Thai Airways International" },
	{ "iata": "MT", "airline": "Thomas Cook Airlines" },
	{ "iata": "FQ", "airline": "Thomas Cook Airlines" },
	{ "iata": "DK", "airline": "Thomas Cook Airlines Scandinavia" },
	{ "iata": "BY", "airline": "Thomson Airways" },
	{ "iata": "3P", "airline": "Tiara Air" },
	{ "iata": "TR", "airline": "Tiger Airways" },
	{ "iata": "TT", "airline": "Tiger Airways Australia" },
	{ "iata": "ZT", "airline": "Titan Airways" },
	{ "iata": "7T", "airline": "Tobruk Air" },
	{ "iata": "9D", "airline": "Toumaï Air Tchad" },
	{ "iata": "WI", "airline": "Tradewinds Airlines" },
	{ "iata": "N4", "airline": "Trans Air Benin" },
	{ "iata": "Q8", "airline": "Trans Air Congo" },
	{ "iata": "M8", "airline": "Trans Maldivian Airways" },
	{ "iata": "TL", "airline": "Trans Mediterranean Airlines" },
	{ "iata": "AX", "airline": "Trans States Airlines" },
	{ "iata": "AL", "airline": "TransAVIAexport Airlines" },
	{ "iata": "GE", "airline": "TransAsia Airways" },
	{ "iata": "UN", "airline": "Transaero Airlines" },
	{ "iata": "T9", "airline": "Transcarga" },
	{ "iata": "TH", "airline": "Transmile Air Services" },
	{ "iata": "5T", "airline": "Transwede Airways" },
	{ "iata": "9T", "airline": "Transwest Air" },
	{ "iata": "GY", "airline": "Tri-MG Intra Asia Airlines" },
	{ "iata": "TN", "airline": "Trigana Air Service" },
	{ "iata": "3A", "airline": "Triple Alpha Luftfahrtgesellschaft" },
	{ "iata": "PM", "airline": "Tropic Air" },
	{ "iata": "2T", "airline": "Tulpar Air Service" },
	{ "iata": "UG", "airline": "TunisAir Express" },
	{ "iata": "TU", "airline": "Tunisair" },
	{ "iata": "3T", "airline": "Turan Air" },
	{ "iata": "TK", "airline": "Turkish Airlines" },
	{ "iata": "T5", "airline": "Turkmenistan Airlines" },
	{ "iata": "T7", "airline": "Twin Jet" },
	{ "iata": "UF", "airline": "UM Airlines" },
	{ "iata": "US", "airline": "US Airways" },
	{ "iata": "UH", "airline": "US Helicopter" },
	{ "iata": "U5", "airline": "USA 3000 Airlines" },
	{ "iata": "UJ", "airline": "USA Jet Airlines" },
	{ "iata": "UT", "airline": "UTair Aviation" },
	{ "iata": "PS", "airline": "Ukraine International Airlines" },
	{ "iata": "6Z", "airline": "Ukrainian Cargo Airways" },
	{ "iata": "B7", "airline": "Uni Air" },
	{ "iata": "UA", "airline": "United Airlines" },
	{ "iata": "4H", "airline": "United Airways (Bangladesh)" },
	{ "iata": "EU", "airline": "United Eagle Airlines" },
	{ "iata": "5X", "airline": "United Parcel Service" },
	{ "iata": "U6", "airline": "Ural Airlines" },
	{ "iata": "HY", "airline": "Uzbekistan Airways" },
	{ "iata": "NN", "airline": "VIM Airlines" },
	{ "iata": "V6", "airline": "VIP Ecuador" },
	{ "iata": "VG", "airline": "VLM Airlines" },
	{ "iata": "RG", "airline": "VRG Linhas Aereas (VARIG)" },
	{ "iata": "LC", "airline": "Varig Logistica (VarigLog)" },
	{ "iata": "RV", "airline": "Venezolana" },
	{ "iata": "VM", "airline": "Viaggio Air" },
	{ "iata": "VI", "airline": "Vieques Air Link" },
	{ "iata": "VN", "airline": "Vietnam Airlines" },
	{ "iata": "4P", "airline": "Viking Airlines" },
	{ "iata": "VQ", "airline": "Vintage Props and Jets" },
	{ "iata": "VX", "airline": "Virgin America" },
	{ "iata": "VS", "airline": "Virgin Atlantic Airways" },
	{ "iata": "DJ", "airline": "Virgin Blue" },
	{ "iata": "VK", "airline": "Virgin Nigeria Airways" },
	{ "iata": "ZG", "airline": "Viva Macau" },
	{ "iata": "VB", "airline": "VivaAerobus" },
	{ "iata": "XF", "airline": "Vladivostok Air" },
	{ "iata": "VA", "airline": "Volare Airlines" },
	{ "iata": "VI", "airline": "Volga-Dnepr Airlines" },
	{ "iata": "VC", "airline": "Voyageur Airways" },
	{ "iata": "VY", "airline": "Vueling Airlines" },
	{ "iata": "W1", "airline": "WDL Aviation" },
	{ "iata": "XW", "airline": "WaltAir" },
	{ "iata": "3W", "airline": "Wan Air" },
	{ "iata": "WT", "airline": "Wasaya Airways" },
	{ "iata": "WJ", "airline": "WebJet Linhas Aéreas" },
	{ "iata": "2W", "airline": "Welcome Air" },
	{ "iata": "PT", "airline": "West Air Sweden" },
	{ "iata": "WS", "airline": "WestJet" },
	{ "iata": "WF", "airline": "Wideroe" },
	{ "iata": "WG", "airline": "Wiggins Airways" },
	{ "iata": "9C", "airline": "Wimbi Dira Airways" },
	{ "iata": "IV", "airline": "Wind Jet" },
	{ "iata": "7W", "airline": "Wind Rose Aviation" },
	{ "iata": "WM", "airline": "Windward Islands Airways" },
	{ "iata": "1W", "airline": "Wings Air" },
	{ "iata": "K5", "airline": "Wings of Alaska" },
	{ "iata": "W6", "airline": "Wizz Air" },
	{ "iata": "W6", "airline": "Wizz Air" },
	{ "iata": "WO", "airline": "World Airways" },
	{ "iata": "8V", "airline": "Wright Air Service" },
	{ "iata": "SE", "airline": "XL Airways France" },
	{ "iata": "9E", "airline": "XL Airways Germany" },
	{ "iata": "MF", "airline": "Xiamen Airlines" },
	{ "iata": "XP", "airline": "Xtra Airways" },
	{ "iata": "R3", "airline": "Yakutia Airlines" },
	{ "iata": "YL", "airline": "Yamal Airlines" },
	{ "iata": "Y8", "airline": "Yangtze River Express" },
	{ "iata": "IY", "airline": "Yemenia - Yemen Airways" },
	{ "iata": "OE", "airline": "Yeongnam Air" },
	{ "iata": "2N", "airline": "Yuzmashavia" },
	{ "iata": "K8", "airline": "Zambia Skyways" },
	{ "iata": "Q3", "airline": "Zambian Airways" },
	{ "iata": "6K", "airline": "Zest Airways" },
	{ "iata": "C4", "airline": "Zimex Aviation" },
	{ "iata": "NMA", "airline": "Nesma Airlines" },
	{ "iata": "FHI", "airline": "Freebird Airlines" }
];

module.exports = function (iata) {
	for (var i = 0; i < airlineIATAs.length; i++) {
		if (airlineIATAs[i].iata == iata) return airlineIATAs[i].airline;
	}
	return null;
}
